### ISSUE TITLE
name 'globalCutOff' is not defined

### ISSUE THREAD

**Issue by tagtag** [lindaszabo/KNIFE#10]
Sorry for sequential submissions.
When I tried to execute ver. 1.5 using sample data set as
nohup sh completeRun.sh /home/tag/circRNA/test/ complete /home/tag/circRNA/test/ testData 8 phred64 circReads 40 2>&1 | tee out_test.log &
I have gotten the error

name 'globalCutOff' is not defined

How can I resolve this problem?

This is similar to closed #7 issue, but I used ver. 1.5, not current master.  Please help me.

**Comment by lindaszabo** [comment]
Version 1.5 is a pre-release version. You should use the released version 1.4
