### ISSUE TITLE
./findCircularRNA.sh: Syntax error: Bad for loop variable

### ISSUE THREAD

**Issue by jxshi** [lindaszabo/KNIFE#16]
KNIFE is recommended by a benchmark paper for its high accuracy. 
I was trying to use KNIFE to find circRNA from RNAseq data. However, I ran into the following error. I have already googled to check if there's any solutions. However, I did not find any useful information. Can you guys check for me please? Thank  you!
My software enviroument:
bowtie: version 1.2
bowtie2: version 2.3.0
perl: version 5.22.0
python: version 2.7.15
R: version 3.2.3
samtools: version 1.7

./findCircularRNA.sh "/data/circRNA/cirires/res/ appended /data/circRNA/cirires/res/ P326 13"
./findCircularRNA.sh: 72: ./findCircularRNA.sh: [[: not found
./findCircularRNA.sh: 83: ./findCircularRNA.sh: [[: not found
cat: /data/circRNA/cirires/res//taskIdFiles/P326.txt: No such file or directory
./findCircularRNA.sh: 144: ./findCircularRNA.sh: Syntax error: Bad for loop variable
completeRun.sh: 57: completeRun.sh: [[: not found
./qualityStatsAll.sh /data/circRNA/cirires/res/ P326 circReads 50 
cat: /data/circRNA/cirires/res//taskIdFiles/P326.txt: No such file or directory
Done looping over qualityStatsSingleSample, awaiting the last few qualityStatsSingleSample.sh to finish 2018/06/03 SUNDAY 22:57:40 CST
./qualityStatsAll.sh: line 49: [: : integer expression expected
cat: '/data/circRNA/cirires/res//P326/sampleStats/*AlignmentStats.txt': No such file or directory
cat: '/data/circRNA/cirires/res//P326/sampleStats/*CircularStats.txt': No such file or directory
rm: cannot remove '/data/circRNA/cirires/res//P326/sampleStats/*AlignmentStats.txt': No such file or directory
rm: cannot remove '/data/circRNA/cirires/res//P326/sampleStats/*CircularStats.txt': No such file or directory
completeRun.sh: 74: completeRun.sh: [[: not found
completeRun.sh: 89: completeRun.sh: [[: not found

**Comment by lindaszabo** [comment]
This is a bash error, and has been reported by a user on Ubuntu (mentioned
in the FAQ here: https://github.com/lindaszabo/KNIFE/tree/master/testData).
Even if you are not using Ubuntu, it could be the same issue so I would
suggest trying to run by explicitly calling bash.

Thank you,
Linda

**Comment by jxshi** [comment]
Hi Linda, 

Thank you for your timely reply. I have already uninstalled dash and tried to call completeRun.sh with bash. Here is the command line that I used:
```
bash completeRun.sh /data/circRNA/cirires/res/ appended /data/circRNA/cirires/res/ P326 13 2>&1 |tee out.log
```
And the same error still pops up. Can you check for me please? By the way, I am currently using Ubuntu 16.04 LTS. Thank  you!

First 5 lines of error code read:
./findCircularRNA.sh "/data/circRNA/cirires/res/ appended /data/circRNA/cirires/res/ P326 13"
./findCircularRNA.sh: 72: ./findCircularRNA.sh: [[: not found
./findCircularRNA.sh: 83: ./findCircularRNA.sh: [[: not found
cat: /data/circRNA/cirires/res//taskIdFiles/P326.txt: No such file or directory
./findCircularRNA.sh: 144: ./findCircularRNA.sh: Syntax error: Bad for loop variable

**Comment by lindaszabo** [comment]
Sorry, I do not have a way to reproduce this so can't provide any more
insight right now. This is a more general bash issue though so hopefully
you can find some information in the bash community to help you
troubleshoot. I will update here if I see any potentially relevant
postings, but again since I can't reproduce it the info I find might not
address your issue.

**Comment by jxshi** [comment]
Hi Linda,

You are right. I tried again by re-configuring ```dash``` using the following command line: ```sudo dpkg-reconfigure dash``` and KNIFE works like a charm now. Thank you guys for your contribution.

Best,

Jianxiang

**Comment by lindaszabo** [comment]
Thank you so much for posting an update on the solution that worked for you
so others are able to access it!
