### ISSUE TITLE
Error in predictJunctions GLM while running KNIFE

### ISSUE THREAD

**Issue by ShobanaSekar** [lindaszabo/KNIFE#5]
Hi,

I am trying to run KNIFE_v1.4 on some of our samples and am running into a few errors for some of them. I am getting these during the call to predictJunctions_tableData.r

**Error 1:**

Error in rbindlist(list(linear_reads, decoy_reads)) : Item 2 has 7 columns, inconsistent with item 1 which has 6 columns. If instead you need to fill missing columns, use set argument 'fill' to TRUE.
Execution halted

**Error 2 (for a different sample):**

Error in fread(classFile, header = TRUE, sep = "\t") :
  File '/scratch/ssekar/circRNA/fastqs_n_tools/ADCC/KNIFE/ADCC_0019_PC_Whole_C1_OV2TD_L02544.proj/ADCC_0019_PC_Whole_C1_OV2TD_L02544.proj/circReads/ids/ADCC_0019_PC_Whole_C1_OV2TD_L02544.proj_R1__output.txt' does not exist. Include one or more spaces to consider the input a system command.

The file fread() complains to be missing is actually present and not empty. I am not sure what else is causing this error. This is all going through fine for 15/20 samples I am running this on. 

It will be really helpful to get your inputs on fixing these errors.

Thank you,
Shobana Sekar

**Comment by lindaszabo** [comment]
For the first error, the only time I have seen this is if there are no decoy reads, which can either happen for very shallowly sequenced libraries or if the wrong read_id_style is used (appended vs complete). 

For the second error, I am not sure why fread would give an error that the file does not exist if it does.

**Comment by rfarouni** [comment]
Hi @ShobanaSekar  @lindaszabo  

I am not sure, but for the second error, the culprit could be the double underscore in "R1__output.txt". The code sometimes adds an underscore to the file name using 'join', like in this [line](https://github.com/lindaszabo/KNIFE/blob/master/circularRNApipeline_Standalone/analysis/filterFDR.py#L96) and sometimes it doesn't, but rather includes it hardcoded in the suffix, just like in this [line](https://github.com/lindaszabo/KNIFE/blob/master/circularRNApipeline_Standalone/analysis/filterFDR.py#L58).

**Comment by ShobanaSekar** [comment]
Sorry this is late, but I was able to resolve this issue by changing the file names of those files that contained an extra "_1" somewhere in its name.

Best
Shobana
