### ISSUE TITLE
Can't Download Indexes

### ISSUE THREAD

**Issue by broughtonjp** [lindaszabo/KNIFE#6]
Hi, I'm trying to download the pre-built indexes for bowtie2 from https://mega.nz/#F!RtsCHCQb!fyxYNWjoCef5Ie361vUxiA but I'm running into trouble since MEGA prevents downloads that are larger than 4-5GB per day. Can these indexes be made available on Amazon, FTP, Dropbox, or another site so that they can be downloaded? Or can you tell me which fasta files are indexed in the the hg19_BT2index folder (i.e. just genome)?

Thanks!

**Comment by lindaszabo** [comment]
What is there is all of the junction indices and genome index. 

You can just recreate them by following the steps in createJunctionIndex to create the indices for a new genome.

**Comment by broughtonjp** [comment]
Okay great!
