### ISSUE TITLE
predictJunctions_tableData.r is not executable

### ISSUE THREAD

**Issue by tagtag** [lindaszabo/KNIFE#9]
If I could understand correctly, 
KNIFE-1.5/circularRNApipeline_Standalone/analysis/predictJunctions_tableData.r
should be executable (presently, not). My job was terminated because of this error.
./predictJunctions.sh: 行 31: ./predictJunctions_tableData.r: 許可がありません
(Thus means, "in Line 31, no permissions" in Japanese)
I did
chmod a+x predictJunctions_tableData.r
to fix it.

**Comment by lindaszabo** [comment]
This is expected behavior, and is mentioned in INSTALL step 2 that the user needs to make the scripts executable.
